### ISSUE TITLE
Add 1.18.2 to curseforge files

### ISSUE THREAD

**Issue by dandin87** [P03W/UpdateFixerUpper#1]
Could you update Curseforge to say that this mod is compatible with 1.18.2? I assume it is also good for all versions in between as well.
Tested it by updating BYG (Oh The Biomes You'll Go) from 1.18.1 to 1.18.2 by fixing Nylium -> Warped as they changed the ID without datafixing it, and would like to include it in AoF5 to ease updating worlds.
byg:nylium_soul_sand -> byg:warped_soul_sand
byg:nylium_soul_soil -> byg:warped_soul_soil

**Comment by SilverAndro** [comment]
Yep can do!
