### ISSUE TITLE
Version 1.0.1 crashes the game on launch

### ISSUE THREAD

**Issue by MScott7** [P03W/UpdateFixerUpper#2]
Version 1.0.1 causes my game to crash on launch, downgrading to version 1.0.0 resolves the issue. 
Minecraft 1.18.2, fabric 0.14.8, fabric api 0.58.0.

Latest.log: https://pastebin.com/uMXJb1rQ
![image](https://user-images.githubusercontent.com/32268672/182011769-8ba460f2-47a3-4009-b0b4-47e6b97edd2c.png)

**Comment by SilverAndro** [comment]
Aw heck

I'll fix this later today, thanks

**Comment by SilverAndro** [comment]
1.0.2 works on 1.18.2+
